### ISSUE TITLE
Feature Request: Hopper Directions

### ISSUE THREAD

**Issue by Darkosto** [LeBossMax2/factinventory#1]
Hello! I love your mod so far! I would love to use this in my new project and was hoping you would be willing to add the ability to make hoppers directional? Not just moving items downwards but potentially left and right? Maybe a right click to change its facing?

Thank you so much and take care!
Darkosto

**Comment by Maaxed** [comment]
It is already possible to rotate hoppers. You just right click with it in your hands.

**Comment by Darkosto** [comment]
Oh! I had no idea, thank you!! :)
